### ISSUE TITLE
router should accept uris like `http://localhost/users/bob`

### ISSUE THREAD

**Issue by antoineverin** [TheSecretOrganization/ft_transcendence#8]
Router should accept uris like `http://localhost/users/bob`

_Originally posted by @antoineverin in https://github.com/TheSecretOrganization/ft_transcendence/issues/5#issuecomment-2254184679_

**Comment by Neffi42** [comment]
but we only have one entrypoint to the api `/api`. Cannot we use something like `http://localhost/api/users/bob`
